/**
 * 分享组件渲染测试文件。
 *
 * 覆盖 ShareCard 与 ShareModal 在多模态场景下的关键展示行为，
 * 确保三维 Hero 固定存在，且辅助图表指标会按真实数据切换到正确口径。
 */

import { render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import ShareCard, { type ShareCardStrings } from "@/components/ShareCard";
import ShareModal from "@/components/ShareModal";
import { extractShareCardData } from "@/lib/shareCardData";
import type { DailyUsage, KeyStats, ParseResult, UsageMetrics } from "@/lib/types";

vi.mock("echarts-for-react", () => ({
  default: ({ option }: { option: unknown }) => (
    <div data-testid="echarts" data-option={JSON.stringify(option)} />
  ),
}));

vi.mock("html2canvas", () => ({
  default: vi.fn(),
}));

vi.mock("qrcode", () => ({
  default: {
    toDataURL: vi.fn().mockResolvedValue("data:image/png;base64,qr"),
  },
}));

vi.mock("@/lib/analytics", () => ({
  trackEvent: vi.fn(),
}));

vi.mock("@/lib/DataContext", () => ({
  useData: vi.fn(),
}));

vi.mock("@/i18n", () => ({
  useTranslation: vi.fn(),
}));

vi.mock("@/lib/ThemeContext", () => ({
  useTheme: vi.fn(),
}));

vi.mock("@/lib/ProjectConfigContext", () => ({
  useProjectConfig: vi.fn(),
}));

import { useData } from "@/lib/DataContext";
import { useTranslation } from "@/i18n";
import { useTheme } from "@/lib/ThemeContext";
import { useProjectConfig } from "@/lib/ProjectConfigContext";

const mockUseData = vi.mocked(useData);
const mockUseTranslation = vi.mocked(useTranslation);
const mockUseTheme = vi.mocked(useTheme);
const mockUseProjectConfig = vi.mocked(useProjectConfig);

/**
 * 构造完整的多模态指标默认值，避免测试夹具遗漏字段。
 */
function createUsageMetrics(overrides: Partial<UsageMetrics> = {}): UsageMetrics {
  return {
    requestCount: 0,
    textRequestCount: 0,
    imageRequestCount: 0,
    videoRequestCount: 0,
    unknownTypeRequestCount: 0,
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    imageCount: 0,
    videoSeconds: 0,
    ...overrides,
  };
}

/**
 * 构造每日聚合记录。
 */
function createDailyUsage(overrides: Partial<DailyUsage>): DailyUsage {
  return {
    date: "2026-06-01",
    model: "agnes-2.0-pro",
    apiKeyName: "Key-A",
    totalCost: 0,
    ...createUsageMetrics(),
    ...overrides,
  };
}

/**
 * 构造 Key 聚合记录。
 */
function createKeyStats(overrides: Partial<KeyStats>): KeyStats {
  return {
    apiKeyName: "Key-A",
    totalCost: 0,
    ...createUsageMetrics(),
    ...overrides,
  };
}

/**
 * 构造最小可用的解析结果，便于聚焦分享展示逻辑测试。
 */
function createParseResult(options: {
  summary: {
    totalCost: number;
    totalTokens: number;
    imageCount: number;
    videoSeconds: number;
    totalRequests: number;
  };
  daily: ParseResult["daily"];
  keys: ParseResult["keys"];
}): ParseResult {
  const summaryMetrics = createUsageMetrics({
    requestCount: options.summary.totalRequests,
    totalTokens: options.summary.totalTokens,
    imageCount: options.summary.imageCount,
    videoSeconds: options.summary.videoSeconds,
  });

  return {
    daily: options.daily,
    keys: options.keys,
    summary: {
      ...summaryMetrics,
      totalCost: options.summary.totalCost,
      totalRequests: options.summary.totalRequests,
      activeKeys: options.keys.length,
      dateRange: { start: "2026-06-01", end: "2026-06-02" },
      models: ["agnes-2.0-pro", "agnes-2.0-flash"],
    },
    warnings: [],
  };
}

/**
 * 提供 ShareCard/ShareModal 所需的最小英文文案。
 */
function createShareCardStrings(): ShareCardStrings {
  return {
    tabLabel: "Overview",
    appName: "Agnes AI Usage Analysis",
    fromLabel: "From",
    textTokensLabel: "Text Tokens",
    imagesLabel: "Images",
    videoSecondsLabel: "Video Seconds",
    requestsLabel: "Requests",
    costLabel: "Cost",
    activeKeysLabel: "Active Keys",
    modelsLabel: "Models",
    projectsLabel: "Projects",
    keysLabel: "Keys",
    chartMetricLabel: "Chart Metric",
    peakLabel: "Peak",
    lowestLabel: "Lowest",
    dailyAverageLabel: "Daily Average",
    generatedBy: "Generated by Agnes",
    scanToVisit: "Scan to visit",
  };
}

/**
 * 提供 ShareModal 所需的最小翻译上下文。
 */
function setupShareModalMocks(result: ParseResult) {
  mockUseData.mockReturnValue({
    filteredResult: result,
  } as ReturnType<typeof useData>);
  mockUseTranslation.mockReturnValue({
    locale: "en",
    setLocale: vi.fn(),
    t: {
      app: {
        title: "Agnes AI Usage Analysis",
      },
      tabs: {
        overview: "Overview",
        projects: "Projects",
        keys: "Keys",
        trends: "Trends",
      },
      metrics: {
        textTokens: "Text Tokens",
        images: "Images",
        videoSeconds: "Video Seconds",
        requests: "Requests",
        cost: "Cost",
      },
      kpi: {
        activeKeys: "Active Keys",
        models: "{count} models",
      },
      overview: {
        chartMetricLabel: "Chart Metric",
      },
      projects: {
        uncategorized: "Uncategorized",
      },
      share: {
        modalTitle: "Share Snapshot",
        from: "From",
        peak: "Peak",
        lowest: "Lowest",
        dailyAverage: "Daily Average",
        generatedBy: "Generated by Agnes",
        scanToVisit: "Scan to visit",
        yourName: "Your Name",
        namePlaceholder: "Mindrose Team",
        nameHint: "Shown on the share image.",
        messageLabel: "Message",
        messagePlaceholder: "Optional message",
        messageHint: "Appears in the top-right corner.",
        generating: "Generating...",
        generateAndCopy: "Generate & Copy",
        downloadPNG: "Download PNG",
        generateFailed: "Generate failed",
        copiedToast: "Copied",
        clipboardUnsupported: "Clipboard unsupported",
        copyFailed: "Copy failed",
        downloadFailed: "Download failed",
      },
    },
  } as ReturnType<typeof useTranslation>);
  mockUseTheme.mockReturnValue({
    theme: "light",
    toggleTheme: vi.fn(),
  } as ReturnType<typeof useTheme>);
  mockUseProjectConfig.mockReturnValue({
    config: [],
    setConfig: vi.fn(),
    matchProject: vi.fn(),
  } as ReturnType<typeof useProjectConfig>);
}

afterEach(() => {
  vi.clearAllMocks();
  localStorage.clear();
});

describe("ShareCard", () => {
  it("在总览模式下固定渲染三维 Hero，并默认展示文本 Token 图表口径", () => {
    const result = createParseResult({
      summary: {
        totalCost: 0,
        totalTokens: 300,
        imageCount: 12,
        videoSeconds: 90,
        totalRequests: 5,
      },
      daily: [
        createDailyUsage({
          date: "2026-06-01",
          apiKeyName: "Key-A",
          requestCount: 4,
          totalTokens: 100,
          imageCount: 2,
          videoSeconds: 30,
        }),
        createDailyUsage({
          date: "2026-06-02",
          model: "agnes-2.0-flash",
          apiKeyName: "Key-B",
          requestCount: 1,
          totalTokens: 200,
          imageCount: 10,
          videoSeconds: 60,
        }),
      ],
      keys: [
        createKeyStats({
          apiKeyName: "Key-A",
          requestCount: 4,
          totalTokens: 100,
          imageCount: 2,
          videoSeconds: 30,
        }),
        createKeyStats({
          apiKeyName: "Key-B",
          requestCount: 1,
          totalTokens: 200,
          imageCount: 10,
          videoSeconds: 60,
        }),
      ],
    });

    const data = extractShareCardData({ tab: "overview", result });

    render(
      <ShareCard
        result={result}
        data={data}
        fromName="Mindrose Team"
        theme="light"
        locale="en"
        qrDataUrl="data:image/png;base64,qr"
        s={createShareCardStrings()}
      />
    );

    expect(screen.getAllByText("Text Tokens").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Images").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Video Seconds").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Chart Metric: Text Tokens").length).toBeGreaterThan(0);

    const option = JSON.parse(screen.getByTestId("echarts").getAttribute("data-option") ?? "{}");
    expect(option.xAxis.data).toEqual(["2026-06-01", "2026-06-02"]);
    expect(option.series[0].data).toEqual([100, 200]);
  });

  it("在 Key 模式下保持三维 Hero 固定，并在无 Token 时切换为图片指标排行", () => {
    const result = createParseResult({
      summary: {
        totalCost: 16,
        totalTokens: 0,
        imageCount: 12,
        videoSeconds: 45,
        totalRequests: 8,
      },
      daily: [
        createDailyUsage({
          date: "2026-06-01",
          apiKeyName: "Key-A",
          requestCount: 3,
          imageRequestCount: 3,
          imageCount: 2,
          videoSeconds: 15,
          totalCost: 4,
        }),
        createDailyUsage({
          date: "2026-06-02",
          model: "agnes-2.0-flash",
          apiKeyName: "Key-B",
          requestCount: 5,
          imageRequestCount: 5,
          imageCount: 10,
          videoSeconds: 30,
          totalCost: 12,
        }),
      ],
      keys: [
        createKeyStats({
          apiKeyName: "Key-A",
          requestCount: 3,
          imageRequestCount: 3,
          imageCount: 2,
          videoSeconds: 15,
          totalCost: 4,
        }),
        createKeyStats({
          apiKeyName: "Key-B",
          requestCount: 5,
          imageRequestCount: 5,
          imageCount: 10,
          videoSeconds: 30,
          totalCost: 12,
        }),
      ],
    });

    const data = extractShareCardData({ tab: "keys", result });

    render(
      <ShareCard
        result={result}
        data={data}
        fromName="Mindrose Team"
        theme="light"
        locale="en"
        qrDataUrl="data:image/png;base64,qr"
        s={{ ...createShareCardStrings(), tabLabel: "Keys" }}
      />
    );

    expect(screen.getAllByText("Text Tokens").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Images").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Video Seconds").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Chart Metric: Images").length).toBeGreaterThan(0);

    const option = JSON.parse(screen.getByTestId("echarts").getAttribute("data-option") ?? "{}");
    expect(option.yAxis.data).toEqual(["Key-A", "Key-B"]);
    expect(option.series[0].data).toEqual([2, 10]);
  });
});

describe("ShareModal", () => {
  it("在预览摘要中展示固定三维 Hero，并同步默认的文本 Token 图表指标", async () => {
    const result = createParseResult({
      summary: {
        totalCost: 0,
        totalTokens: 300,
        imageCount: 12,
        videoSeconds: 90,
        totalRequests: 5,
      },
      daily: [
        createDailyUsage({
          date: "2026-06-01",
          apiKeyName: "Key-A",
          requestCount: 4,
          totalTokens: 100,
          imageCount: 2,
          videoSeconds: 30,
        }),
        createDailyUsage({
          date: "2026-06-02",
          model: "agnes-2.0-flash",
          apiKeyName: "Key-B",
          requestCount: 1,
          totalTokens: 200,
          imageCount: 10,
          videoSeconds: 60,
        }),
      ],
      keys: [
        createKeyStats({
          apiKeyName: "Key-A",
          requestCount: 4,
          totalTokens: 100,
          imageCount: 2,
          videoSeconds: 30,
        }),
        createKeyStats({
          apiKeyName: "Key-B",
          requestCount: 1,
          totalTokens: 200,
          imageCount: 10,
          videoSeconds: 60,
        }),
      ],
    });

    setupShareModalMocks(result);

    render(<ShareModal tab="overview" onClose={vi.fn()} />);

    await waitFor(() => {
      expect(screen.getAllByText("Chart Metric: Text Tokens").length).toBeGreaterThan(0);
    });

    expect(screen.getAllByText("Text Tokens").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Images").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Video Seconds").length).toBeGreaterThan(0);
  });

  it("在趋势预览摘要中保留三维 Hero，并在无 Token 时回退为图片指标", async () => {
    const result = createParseResult({
      summary: {
        totalCost: 16,
        totalTokens: 0,
        imageCount: 12,
        videoSeconds: 45,
        totalRequests: 8,
      },
      daily: [
        createDailyUsage({
          date: "2026-06-01",
          apiKeyName: "Key-A",
          requestCount: 3,
          imageRequestCount: 3,
          imageCount: 2,
          videoSeconds: 15,
          totalCost: 4,
        }),
        createDailyUsage({
          date: "2026-06-02",
          model: "agnes-2.0-flash",
          apiKeyName: "Key-B",
          requestCount: 5,
          imageRequestCount: 5,
          imageCount: 10,
          videoSeconds: 30,
          totalCost: 12,
        }),
      ],
      keys: [
        createKeyStats({
          apiKeyName: "Key-A",
          requestCount: 3,
          imageRequestCount: 3,
          imageCount: 2,
          videoSeconds: 15,
          totalCost: 4,
        }),
        createKeyStats({
          apiKeyName: "Key-B",
          requestCount: 5,
          imageRequestCount: 5,
          imageCount: 10,
          videoSeconds: 30,
          totalCost: 12,
        }),
      ],
    });

    setupShareModalMocks(result);

    render(<ShareModal tab="trends" onClose={vi.fn()} />);

    await waitFor(() => {
      expect(screen.getAllByText("Chart Metric: Images").length).toBeGreaterThan(0);
    });

    expect(screen.getAllByText("Text Tokens").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Images").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Video Seconds").length).toBeGreaterThan(0);
  });
});
